# 2 文本数据处理

## 2.1 词嵌入
词嵌入的根本目的是为了**将非数值数据转换为向量**，这样才能放入计算机进行运算。常见词嵌入的有**Word2Vec**。在GPT架构中，没有使用这一技术，GPT3的嵌入大小达到了12288维。其中，GPT将词嵌入作为训练模型，不断调整。也就是说，**GPT将词嵌入这一部分也进行训练**。

![1716433691383](../image/从零开始构建LLM/1716433691383.png)


## 2.2 标记文本
标记文本就是将文本进行拆分，拆分为单个单词后，对每个单词进行唯一映射。可以使用字典进行标记，将每个单词映射为token id，再使用token id进行词嵌入。

In [1]:
import os, re

In [2]:
filepath = os.path.join('..', 'data', 'the-verdict.txt')
assert os.path.exists(filepath), f"{filepath} is not exists."
with open(filepath) as f:
    raw_text = f.read()
print(">> Total number of character:", len(raw_text))
print(">> raw text:", raw_text[:100])
print()

# split raw text
preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)
preprocessed = [item.strip() for item in preprocessed if item.strip()]  # remove empty string
print(">> preprocessed:", preprocessed[:30])
print(">> length:", len(preprocessed))
print()

# remove duplicate words
all_words = sorted(set(preprocessed))
vocab_size = len(all_words)
print(">> size of vocab after removed duplicate words:", vocab_size)

# create vocab
vocab = {token:integer for integer,token in enumerate(all_words)}
print(">> vocab: front 20 items")
for tok, i in vocab.items():
    if i > 20:
        break
    print(tok, i)

>> Total number of character: 20479
>> raw text: I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no g

>> preprocessed: ['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in']
>> length: 4690

>> size of vocab after removed duplicate words: 1130
>> vocab: front 20 items
! 0
" 1
' 2
( 3
) 4
, 5
-- 6
. 7
: 8
; 9
? 10
A 11
Ah 12
Among 13
And 14
Are 15
Arrt 16
As 17
At 18
Be 19
Begin 20


上述代码展示了如下过程

![1716433945337](../image/从零开始构建LLM/1716433945337.png)

字典表的创建方式可以通过自己创建，通过创建后的字典表，可以实现文本与token id之间的互相转换。

进一步的，可以将其封装为类

In [3]:
class SimpleTokenizerV1:
    def __init__(self, vocab):  # our vocab
        self.str_to_int = vocab
        self.int_to_str = {i:s for s,i in vocab.items()}  # reverse k, v
    
    def encode(self, text):  # our text
        preprocessed = re.split(r'([,.?_!"()\']|--|\s)', text)
        preprocessed = [
            item.strip() for item in preprocessed if item.strip()  # remove empty string
        ]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
        
    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        # Replace spaces before the specified punctuations
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text

tokenizer = SimpleTokenizerV1(vocab)

text = """"It's the last he painted, you know," 
           Mrs. Gisburn said with pardonable pride."""
print(">> original text: ", text)

ids = tokenizer.encode(text)
print(">> encoded data:", ids)

decoded_text = tokenizer.decode(ids)
print(">> decoded data:", decoded_text)

>> original text:  "It's the last he painted, you know," 
           Mrs. Gisburn said with pardonable pride.
>> encoded data: [1, 56, 2, 850, 988, 602, 533, 746, 5, 1126, 596, 5, 1, 67, 7, 38, 851, 1108, 754, 793, 7]
>> decoded data: " It' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.


![1716434053588](../image/从零开始构建LLM/1716434053588.png)

## 2.3 特殊处理


正如一般的数据预处理流程，文本中的异常数据也应当注意。当上述字典表覆盖不全面时，针对不在字典表中的字符就需要特殊处理，并且不同句子之间，也需要分割符。</br>

**为未知单词加入一些特殊标记**是非常有用的。作用如下：

* 使用特殊标记来帮助 LLM 提供额外的上下文
* 注：一些特殊标记如下<br/>
    1. [BOS] Beginning of sequence. 文本开始<br/>
    2. [EOS] end of sequence. 文本结束<br/>
    3. [PAD] padding. 使训练文本长度统一<br/>
    [UNK] 未知字符，不在字典表中<br/>
* GPT-2中仅使用`<|endoftext|>`减少复杂性，`<|endoftext|>`与`[EOS]`用法类似。GPT-2同时使用`<|endoftext|>`来进行PAD操作。
* 对于未知单词，GPT-2未使用[UNK]进行替代，而是使用字节对编码-(byte-pair encoding, BPE)将单词进行分解。

因此在上述V1版本上，我们需要进行改进，将未知字符与分割符加入字典表中：

`all_tokens.extend(["<|endoftext|>", "<|unk|>"])`

![1716455910828](../image/从零开始构建LLM/1716455910828.png)

In [4]:
preprocessed = re.split(r'([,.?_!"()\']|--|\s)', raw_text)
preprocessed = [item.strip() for item in preprocessed if item.strip()]

all_tokens = sorted(list(set(preprocessed)))

# === append two special tokens ===
all_tokens.extend(["<|endoftext|>", "<|unk|>"])

vocab = {token:integer for integer,token in enumerate(all_tokens)}

vocab_size = len(vocab)
print(">> size of vocab after removed duplicate words:", vocab_size)

print(">> vocab: last 5 items")
for i, tok in enumerate(list(vocab.items())[-5:]):
    print(tok)

>> size of vocab after removed duplicate words: 1161
>> vocab: last 5 items
('younger', 1156)
('your', 1157)
('yourself', 1158)
('<|endoftext|>', 1159)
('<|unk|>', 1160)


同样的，将其封装为类

In [5]:
class SimpleTokenizerV2:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = { i:s for s,i in vocab.items()}
    
    def encode(self, text):
        preprocessed = re.split(r'([,.?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        preprocessed = [
            item if item in self.str_to_int 
            else "<|unk|>" for item in preprocessed
        ]

        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
        
    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        # Replace spaces before the specified punctuations
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text


tokenizer = SimpleTokenizerV2(vocab)

text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."

text = " <|endoftext|> ".join((text1, text2))

print(">> input text:", text)

ids = tokenizer.encode(text)
print(">> encoded data:", ids)

decoded_text = tokenizer.decode(ids)
print(">> decoded data:", decoded_text)

>> input text: Hello, do you like tea? <|endoftext|> In the sunlit terraces of the palace.
>> encoded data: [1160, 5, 362, 1155, 642, 1000, 10, 1159, 57, 1013, 981, 1009, 738, 1013, 1160, 7]
>> decoded data: <|unk|>, do you like tea? <|endoftext|> In the sunlit terraces of the <|unk|>.


## 2.4 字节对编码（Byte pair encoding, BPE）

In [6]:
import tiktoken

In [7]:
tokenizer = tiktoken.get_encoding("gpt2")

text = "Hello, do you like tea? <|endoftext|> In the sunlit terraces of someunknownPlace."

ids = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
print(">> encoded data:", ids)

decoded_text = tokenizer.decode(ids)
print(">> decoded data:", decoded_text)

>> encoded data: [15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 286, 617, 34680, 27271, 13]
>> decoded data: Hello, do you like tea? <|endoftext|> In the sunlit terraces of someunknownPlace.


> BPE会将未知单词拆分成独立个体的单词

![1716778401378](../image/从零开始构建LLM/1716778401378.png)

## 2.5 使用滑窗进行数据采样

![1716778580547](../image/从零开始构建LLM/1716778580547.png)

从上图可以看到，滑窗采样其实就是每次往后间隔进行采样。下面进行代码实现：

In [8]:
enc_text = tokenizer.encode(raw_text)
enc_sample = enc_text[50:]

context_size = 4
x = enc_sample[:context_size]
y = enc_sample[1:context_size + 1]
print(f">> x: {x}")
print(f">> y: {y}")
print()

print(">> tokenizer encode in one context:")
for i in range(1, context_size + 1):
    context = enc_sample[:i]
    desired = enc_sample[i]
    print(f">> {context} --> {desired}")
print()

print(">> tokenizer decode in one context:")
for i in range(1, context_size + 1):
    context = enc_sample[:i]
    desired = enc_sample[i]
    print(f">> {tokenizer.decode(context)} --> {tokenizer.decode([desired])}")

>> x: [290, 4920, 2241, 287]
>> y: [4920, 2241, 287, 257]

>> tokenizer encode in one context:
>> [290] --> 4920
>> [290, 4920] --> 2241
>> [290, 4920, 2241] --> 287
>> [290, 4920, 2241, 287] --> 257

>> tokenizer decode in one context:
>>  and -->  established
>>  and established -->  himself
>>  and established himself -->  in
>>  and established himself in -->  a


因此，我们主要关心的只有两个向量，输入和输出， 并且输入输出可以通过不同的步长来进行修改。

![1716778596288](../image/从零开始构建LLM/1716778596288.png)

In [9]:
import torch
from torch.utils.data import Dataset, DataLoader


class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        # Tokenize the entire text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})

        # Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]


def create_dataloader_v1(txt, batch_size=4, max_length=256, 
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):

    # Initialize the tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")

    # Create dataset
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

    # Create dataloader
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=0
    )

    return dataloader

> 注：这一部分可以通过修改batch_size, max_length, stride参数来观察输出变化

In [10]:
# modify: batch_size, max_length, stride
# will get different data
dataloader = create_dataloader_v1(
    raw_text, batch_size=2, max_length=4, stride=2, shuffle=False
)

data_iter = iter(dataloader)
data = next(data_iter)
print(f">> data shape: {data[0].shape}")
print(f">> {data}")

>> data shape: torch.Size([2, 4])
>> [tensor([[  40,  367, 2885, 1464],
        [2885, 1464, 1807, 3619]]), tensor([[ 367, 2885, 1464, 1807],
        [1464, 1807, 3619,  402]])]


## 2.6 创建token嵌入

这一部分将token id转换为嵌入向量，使用torch自带的nn.Embedding

![1716778710812](../image/从零开始构建LLM/1716778710812.png)

In [11]:
# Simple Example
input_ids = torch.tensor([2, 3, 5, 1])

vocab_size = 6
output_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
print(f">> {embedding_layer.weight}")

print(f">> {embedding_layer(input_ids)}")

>> Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)
>> tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


## 2.7 编码位置向量

当token id一致时，使用同一个词嵌入会得到相同输出，如下图所示，对于数字5，其词嵌入向量一致。

![1716778847577](../image/从零开始构建LLM/1716778847577.png)

但是在本文生成任务中，这是不可取的，因为文本前后是有关联的。为了解决这一问题，引入了位置编码，这样可以保证每一个编码是独一无二的

![1716778935403](../image/从零开始构建LLM/1716778935403.png)

最后，所有的数据处理流程如下：

![1716778990725](../image/从零开始构建LLM/1716778990725.png)


In [12]:
vocab_size = 50257
output_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

max_length = 4
dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=max_length, stride=max_length, shuffle=False)

data_iter = iter(dataloader)

inputs, targets = next(data_iter)
print(f">> Token IDs:\n {inputs}")
print(f">> Inputs shape: {inputs.shape}")

token_embeddings = token_embedding_layer(inputs)
print(f">> {token_embeddings.shape}")
# >> (8, 4, 256) -> 8: batch_size, 4: max_length, 256: output_dim

context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)
pos_embeddings = pos_embedding_layer(torch.arange(context_length))
print(f">> pos embeddings's shape: {pos_embeddings.shape}")

input_embeddings = token_embeddings + pos_embeddings
print(f">> input embeddings's shape: {input_embeddings.shape}")

>> Token IDs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
>> Inputs shape: torch.Size([8, 4])
>> torch.Size([8, 4, 256])
>> pos embeddings's shape: torch.Size([4, 256])
>> input embeddings's shape: torch.Size([8, 4, 256])
